# Generated by Django 5.0.4 on 2024-04-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytical_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100)),
                ('method_description', models.TextField()),
                ('sample_matrix', models.CharField(max_length=50)),
                ('cost_per_sample', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
