# Generated by Django 5.0.4 on 2024-05-01 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('sample_type', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid'), ('Gas', 'Gas')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticalMethod',
            fields=[
                ('method_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('method_description', models.TextField()),
                ('cost_per_sample', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='an_organ.instrument')),
            ],
        ),
    ]
