# Generated by Django 5.0.4 on 2024-04-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('sample_type', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid'), ('Gas', 'Gas')], max_length=10)),
                ('price_per_sample', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Analytical_Method',
            fields=[
                ('method_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('method_description', models.TextField()),
                ('sample_matrix', models.CharField(max_length=50)),
                ('cost_per_sample', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='an_organ.instrument')),
            ],
        ),
    ]
