# Generated by Django 5.0.4 on 2024-05-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('an_organ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethod',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='an_organ.instrument'),
        ),
    ]
