# Generated by Django 5.0.4 on 2024-05-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('an_organ', '0002_alter_analyticalmethod_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticalmethod',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='instrument_id',
        ),
        migrations.AddField(
            model_name='analyticalmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyticalmethod',
            name='method_name',
            field=models.CharField(max_length=100),
        ),
    ]
